services:
  # NestJS Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    container_name: citizengate-server
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: ${DATABASE_URL}
      CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      SUPABASE_URL: ${SUPABASE_URL}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      PLUNK_API_KEY: ${PLUNK_API_KEY}
    ports:
      - "${SERVER_PORT:-3000}:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - citizengate-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Vite Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    container_name: citizengate-client
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}
      VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
    ports:
      - "${CLIENT_PORT:-5173}:5173"
    volumes:
      # Only mount source code in development
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - citizengate-network
    command: >
      sh -c "if [ '${NODE_ENV:-development}' = 'production' ]; then
               nginx -g 'daemon off;'
             else
               pnpm run dev --host 0.0.0.0
             fi"

networks:
  citizengate-network:
    driver: bridge
